config/routes.rb
Rails.application.routes.draw do

  resources :book_posts
  resources :pages

  root 'pages#index'

  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  } do
  end

  get 'enable_otp_show_qr', to: 'users#enable_otp_show_qr', as: 'enable_otp_show_qr'
  post 'enable_otp_verify', to: 'users#enable_otp_verify', as: 'enable_otp_verify'

  get 'users/otp', to: 'users#show_otp', as: 'user_otp'
  post 'users/otp', to: 'users#verify_otp', as: 'verify_user_otp'
  post 'verify_otp', to: 'users/sessions#verify_otp'

  resources :admin, only: [:index, :create, :update, :destroy]

  # get 'admin/index'
  # post '/admin/users', to: 'admin#create', as: 'admin_users'
  # patch '/admin/users/:id', to: 'admin#update', as: 'admin_user'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book_post.rb
class BookPost < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :genre, presence: true
  validates :isbn, presence: true, uniqueness: true, format: { with: /\A[\d-]+\z/, message: "only allows numbers and hyphens" }

  scope :sorted, ->{ order(published_at: :desc, updated_at: :desc) } 

  belongs_to :user

end

app/controllers/book_posts_controller.rb
class BookPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_book_post, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @book_posts = BookPost.all
  end

  def new
    @book_post = BookPost.new
  end

  def create
    @book_post = current_user.book_posts.build(book_post_params)
    if @book_post.save
      redirect_to @book_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @book_post.update(book_post_params)
      redirect_to @book_post
    else
      render :edit, status: :unprocessable_entity
  end
end

  def destroy
    @book_post.destroy
    redirect_to root_path
  end

  private

  def book_post_params
    params.require(:book_post).permit(:title, :author, :genre, :isbn)
  end

  def set_book_post
    @book_post = BookPost.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def check_user
    unless @book_post.user_id == current_user.id || current_user.admin?
      redirect_to root_path
    end
  end
end

app/views/book_posts/_form.html.erb
<%= form_with model: @book_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
      <% end %>
    </div>
    <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div>
    <%= form.label :isbn %>
    <%= form.text_field :isbn %>
  </div>



  <%= form.button %>
<% end %>

app/views/book_posts/edit.html.erb
<h1>Edit blog post</h1>

<%= render partial: "form", locals: {book_post: @book_post} %>

<%= button_to "Delete", @book_post, method: :delete, data: {turbo_confirm: "Are you sure?"} %>

app/views/book_posts/index.html.erb
<%
=begin%>
 
 <div class="relative">
  <div class="mt-5">
    <h2 class="text-2xl font-bold">My Library</h1>
  </div>
  <div>
      <% @book_posts.each do |book_post| %>
      <div class="mt-4">
        <h2 class="text-xl font-bold underline"><%= link_to book_post.title, book_post %></h2>
      </div>
    <% end %>
  </div>
</div>  
<%
=end
%>

app/views/book_posts/new.html.erb
<h1>New book post</h1>

<%= render partial: "form", locals: {book_post: @book_post} %>

app/views/book_posts/show.html.erb
<div class="mt-2">
  <p>
    <strong>Posted by:</strong>
    <%= @book_post.user.username %>
  </p>
  <h1 class="font-bold text-2xl py-2"><%= @book_post.title %></h1>
  <div class="inline-block">
    <h2 class="font-bold">Auteur: <p class="font-normal"><%= @book_post.author %></p></h2>
    <h2 class="font-bold">Genre: <p class="font-normal"><%= @book_post.genre %></p></h2>
    <h2 class="font-bold">ISBN: <p class="font-normal"><%= @book_post.isbn %></p></h2>
  </div><br />
  <button class="mt-4 border-2 border-gray-400 p-4">
    <% if current_user && (@book_post.user == current_user || current_user.admin?) %>
    <%= link_to 'Edit', edit_book_post_path(@book_post), class: 'p-4' %>
  <% end %>
  </button>
</div>