config/routes.rb
Rails.application.routes.draw do

  resources :book_posts
  resources :pages

  root 'pages#index'

  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  } do
  end

  get 'enable_otp_show_qr', to: 'users#enable_otp_show_qr', as: 'enable_otp_show_qr'
  post 'enable_otp_verify', to: 'users#enable_otp_verify', as: 'enable_otp_verify'

  get 'users/otp', to: 'users#show_otp', as: 'user_otp'
  post 'users/otp', to: 'users#verify_otp', as: 'verify_user_otp'
  post 'verify_otp', to: 'users/sessions#verify_otp'

  resources :admin, only: [:index, :create, :update, :destroy]

  # get 'admin/index'
  # post '/admin/users', to: 'admin#create', as: 'admin_users'
  # patch '/admin/users/:id', to: 'admin#update', as: 'admin_user'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="relative flex w-full">
    <div class="">
      <p class="font-bold"><%= link_to "Bibliotheek", root_path %></p>
    </div>
    <div class="inline-flex ml-auto gap-x-5">
      <% if user_signed_in? %>
        <div class=""><h2>Logged in as <b><%= current_user.username %></b></h2></div>
      <p class=""><%= link_to "New book post", new_book_post_path %></p>  
        <%= link_to "Admin", admin_index_path if current_user.admin? %>
        <p><%= link_to "Profile", edit_user_registration_path %></p>
        <p class=""><%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete } %></p><br />
        <%= image_tag(current_user.avatar_thumbnail) %>
        <%
=begin%>
 <%= raw RQRCode::QRCode.new(current_user.otp_provisioning_uri(current_user.email, issuer: "Devise-Two-Factor-Demo"), 
        :svg, 
        :level => :h,
        :size => 10,
        :unit => 2).as_svg %> 
<%
=end
%>
      <% else %>
        <p><%= link_to "Sign In", new_user_session_path %></p>
        <p><%= link_to "Sign Up", new_user_registration_path %></p>
      <% end %>
    </div>
  </div>

    <%= yield %>
  </body>
</html>